# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Combinestagram' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Combinestagram

  pod 'RxSwift'
  pod 'RxCocoa'

  target 'CombinestagramTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CombinestagramUITests' do
    # Pods for testing
  end

end
