# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RealmProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RealmProject
  pod 'RealmSwift', '=10.1.4'

  target 'RealmProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RealmProjectUITests' do
    # Pods for testing
  end

end
