# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WebViewPage' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WebViewPage
  pod 'SideMenu'

  target 'WebViewPageTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WebViewPageUITests' do
    # Pods for testing
  end

end
