# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxSwift-Filter' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxSwift-Filter
  pod 'RxSwift'
  pod 'RxCocoa'

  target 'RxSwift-FilterTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RxSwift-FilterUITests' do
    # Pods for testing
  end

end
