# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Realm' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Realm
  pod 'RealmSwift', '=10.1.4'

  target 'RealmTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RealmUITests' do
    # Pods for testing
  end

end
